#!/bin/bash
echo "ALX"
root@74fc5faec46f:/alx-pre_course/0x01-git/bash# clear

clear
root@74fc5faec46f:/alx-pre_course/0x01-git/bash# clear
exit
root@74fc5faec46f:/alx-pre_course/0x01-git/bash# clear
root@74fc5faec46f:/alx-pre_course/0x01-git/bash# exit
